apiVersion: v1
kind: Service
metadata:
  name: kubeserve-canary
spec:
  type: {{ .Values.service.type }}
  slector:
    app: kubeserve
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
